server.port=8080

spring.application.name=gus-company-finder

bdl.api.base-url=https://bdl.stat.gov.pl/api/v1
bdl.api.client-id=${BDL_CLIENT_ID:}
bdl.api.default-page-size=20

cors.allowed-origins=http://localhost:5173
